### ISSUE TITLE
Invalid number on fish

### ISSUE THREAD

**Issue by big-hero-dev** [G2-Games/welcome-sh#1]
![welcome](https://user-images.githubusercontent.com/43630437/190945179-1b7d3cef-2e3d-4a46-bfdc-1d5090ea7396.png)

**Comment by G2-Games** [comment]
Interesting, I didn't know if it supported fish at all... as a temporary fix, you could change the `USRC` variable from `$(randcolor)` to something like `'\e[38;2;50;168;82;1m'`

Please let me know if this fixes it, if not, I can try to work with you on a fix

**Comment by G2-Games** [comment]
In fact, Fish doesn't work for me at all, I get an error:
![image](https://user-images.githubusercontent.com/72430668/190946928-7d651c91-5c1d-4a22-8f88-0fdb9cd91237.png)

**Comment by big-hero-dev** [comment]
Yeah! It worked, but I feed my terminal delay a couple of seconds when switch workspace :(

**Comment by G2-Games** [comment]
That is probably due to the update checker, what distro are you on?
You can disable it by commenting out the `updates` line

**Comment by big-hero-dev** [comment]
I use Manjaro with bspwm. I will disable updates .

**Comment by G2-Games** [comment]
Sounds good, thank you for using it

**Comment by big-hero-dev** [comment]
> Sounds good, thank you for using it

It faster now thank for your help :v:

**Comment by Remynfv** [comment]
As a quick hack you can run it through bash whenever you start fish:

```
function fish_greeting
    bash ~/.welcome/welcome.sh
end
funcsave fish_greeting```

**Comment by G2-Games** [comment]
Yes, that is a good solution. I guess the optimal solution would be to rewrite it in fish for optimal support
