### ISSUE TITLE
Invalid Number Error (printf)

### ISSUE THREAD

**Issue by ClonkDroid** [G2-Games/welcome-sh#3]
Every run of the Script, printf complains about an invalid number: 

`./welcome.sh: Zeile 164: printf: 37.378: Ungültige Zahl.`
Translation:
`./welcome.sh: Line 164: printf: 37.378: Invalid Number.`

The number is random every run, considering the error is spawned in the random number generator.

FIX:
adding `export LC_NUMERIC="en_US.UTF-8"` to my .bashrc fixed it.
Maybe that should be added to the description

**Comment by G2-Games** [comment]
Interesting, I'll look into it, I assume this is a unicode issue then

**Comment by G2-Games** [comment]
I think my solution will be to add `export LC_NUMERIC="en_US.UTF-8"` to the beginning of the Welcome script, to ensure numbers are processed properly

**Comment by G2-Games** [comment]
@ClonkDroid I pushed an update that should hopefully fix it, if you update you should be good!

**Comment by ClonkDroid** [comment]
Sadly, adding it to the end of the file doesnt work for some reason. I have created a new commit placing the statement in the right place

**Comment by G2-Games** [comment]
Oh, thank you. I'll merge it, and push an update
